# REQUIRED
#    permissions:
#      contents: 'read'
#      id-token: 'write'

name: "Setup Docker Credentials"
runs:
  using: "composite"
  steps:
    - uses: 'google-github-actions/auth@v2'
      id: auth
      with:
        project_id: 'kouzoh-p-nurlashko'
        workload_identity_provider: 'projects/5480347068/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'blog-ci@kouzoh-p-nurlashko.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: 'Configure Docker'
      run: gcloud auth configure-docker
