name: _scratch CI

on:
  push:
    paths:
      - 'microservices/_scratch/**'
  workflow_dispatch:
jobs:

  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build microservices/_scratch -t gcr.io/kouzoh-p-nurlashko/nurlashko/_scratch
    - name: Push the Docker image
      env:
        CR_LOGIN: ${{ secrets.CR_LOGIN }}
        CR_PASS: ${{ secrets.CR_PASS }}
      run: |
        echo "$CR_PASS" | docker login --username="$CR_LOGIN" --password-stdin https://gcr.io    
        docker push gcr.io/kouzoh-p-nurlashko/nurlashko/_scratch
