FROM jonasal/nginx-certbot:3.1.2-alpine

ENV CERTBOT_EMAIL=zh.nurlan96@gmail.com

#COPY configs/ /etc/nginx/conf.d/
COPY configs/blog.conf /etc/nginx/conf.d/blog.conf
COPY include/ /etc/nginx/include/
