name: "Build And Push Docker Image"
inputs:
  microservice:
    required: true
  repoflow_pwd:
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: api.repoflow.io
        username: nurlashko
        password: ${{ inputs.REPOFLOW_PWD }}
    -
      name: Build And Push Docker Image
      run: |
        docker build microservices/${{ inputs.microservice }} -t api.repoflow.io/zhnurlan96-5303/blog/${{ inputs.microservice }}:test
        docker push api.repoflow.io/zhnurlan96-5303/blog/${{ inputs.microservice }}