name: "Build And Push Docker Image"
inputs:
  microservice:
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: api.repoflow.io
        username: nurlashko
        password: ${{ secrets.REPOFLOW_PWD }}