apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: database 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi