name: Prometheus CI

on:
  push:
    paths:
      - 'microservices/prometheus/**'
  workflow_dispatch:
env:
  MICROSERVICE: prometheus
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'
      - name: Setup Docker Credentials
        uses: 'NurlashKO/blog/.github/actions/setup-docker-credentials@main'
      - name: Build && Push Docker image
        run: |
          docker build microservices/$MICROSERVICE -t gcr.io/kouzoh-p-nurlashko/nurlashko/$MICROSERVICE
          docker push gcr.io/kouzoh-p-nurlashko/nurlashko/$MICROSERVICE
